os: linux
sudo: false
dist: trusty

language: java
jdk: oraclejdk8

cache:
  directories:
    - '~/.m2/repository'

install:
  # Resolve all dependencies
  - mvn -B -V -q -DskipTests install

script:
  # Build and test with code coverage (add `verify sonar:sonar` to enable the Sonar analysis)
  - mvn -B jacoco:prepare-agent test jacoco:report jacoco:report-aggregate

after_success:
  - bash <(curl -s https://codecov.io/bash)
